### ISSUE TITLE
Change check to Safebrowsing v4 API

### ISSUE THREAD

**Issue by Zodiac1978** [pluginkollektiv/antivirus#42]
Version 2 and 3 are deprecated and shutdown:
https://security.googleblog.com/2018/01/announcing-turndown-of-deprecated.html

Therefore we get now false alarm mails (or is the API key invalid?)
https://github.com/pluginkollektiv/antivirus/blob/08d6d04260312f7aa91db5ab56df5a65f8b572a7/antivirus.php#L289

We should move to the new v4 API:
https://developers.google.com/safe-browsing/v4/lookup-api

**Comment by Zodiac1978** [comment]
Two thoughts after some debugging:

**Should we disclose the API key this openly in our code?**

> Speichern Sie API-Schlüssel nicht in Dateien in der Quellstruktur der Anwendung. Wenn Sie API-Schlüssel in Dateien speichern, sollten sich diese außerhalb der Quellstruktur der Anwendung befinden, um sicherzustellen, dass Ihre Schlüssel nicht im Verwaltungssystem des Quellcodes landen. Dies ist besonders wichtig, wenn Sie ein öffentliches Quellcode-Verwaltungssystem wie GitHub verwenden

**The API key is valid, but the final shutdown of the service seems to be delayed until now**

**Comment by Zodiac1978** [comment]
And another problem:
> A single API key can make requests for up to 10,000 clients per 24-hour period.
https://developers.google.com/safe-browsing/v4/usage-limits

We have 70k active installations and a **daily** cron job. This couldn't work.

**Comment by stklcode** [comment]
In my opinion the fixed key should be removed.
Not because the "secret" key is disclosed but because it simply does not scale with shared key around all sites, as you already discovered.

The feature could be refactored to an Opt-In feature and the administrator has to enter a custom API key (as it's done with various restricted APIs in other plugins).

Another obvious thought is introducing a custom API service that throttles the request. It's probably possible to obtain a higher quota to meet the required number of requests (pretty sure such request would be rejected with an open key as it it right now). This custom API must limit requests itself to prevent misuse and quota exceeding (for malicious reasons or just because a certain number of admins are paranoid enough to add an hourly cron job or so). However it increases responsibility and maintenance workload, so I'd prefer the above solution.

**Comment by KittMedia** [comment]
I would also suggest the first solution from @stklcode because the second one doesn’t even fix the limit problem as there already are too many installations to use a single key on a daily base. And Google doesn’t like it to use a bunch of different keys for the same purpose (I already tried that in another project 😬).

**Comment by Zodiac1978** [comment]
Although I'm with you here, we have no data about the real usage as we have no control of the API Key and therefore we can't see any real usage numbers. This feature needs to be manually enabled and we do not know how many people are using it.

Therefore I will go with the solution from @2ndkauboy in #43 with the addition that I created a new API key that I can monitor. I would suggest to fix this issue fast with the new key and then check the real usage numbers. If we really exceed the limits we will ask for the API key in a new version.
